### ISSUE TITLE
Système de messagerie entre utilisateurs

### ISSUE THREAD

**Issue by zyzo** [RemiPrevost/ProjectWebRTC#4]
Système qui permet d'échanger et stocker les messages entre utilisateurs, avec notification

**Comment by jauffretp** [comment]
J'ai commencé a travailler dessus, j'arrive à inserer des messages, mais il faut que je retravaille le publish/subscribe pour autoriser seulement le client a avoir accès aux bons messages

**Comment by RemiPrevost** [comment]
Tu peux jeter un coup d'oeil à ce que j'ai fait pour le système de chat. J'ai utilisé le système de publish/subscribe et ça marche très bien! Je travaille sur la branche dev.

**Comment by jauffretp** [comment]
Je viens de jeter un petit coup d'oeil. Je viens d'arriver à faire ce que je voulais. Je ne display plus que les bons messages, j'ai bien galérer sur des petits détails a la con ( genre oublier le fetch et me taper un undefined ....).
Sinon, je l'ai fait mais jai pas forcément compris pourquoi, à quoi ça sert de mettre le subscribe dans le Deps.autorun, j'ai lu un peu la doc de meteor et normalement il doit y avoir une new Deps.dependency sur le login, mais j'ai pas trouvé.

**Comment by jauffretp** [comment]
Système a peu près fonctionnel, mais par contre il y a une exception que je ne comprends pas du tout.

Sinon, il faut que j'améliore l'affichage des messages, qui sont pour l'instant simplement dans une liste, il faudrait les trier par dates et par utilisateur.

**Comment by RemiPrevost** [comment]
C'est bizarre ce Deps. Je ne m'en suis pas servi et pourtant j'ai l'impression que ça marche bien...

**Comment by jauffretp** [comment]
Bon, je comprends rien.

Ma version marchait a peu près, et la je réessaie et plus rien ne marche. J’étais en train d'essayer de rajouter les dates, un truc qui n'a rien a voir. Maintenant je me tape l'exception de partout, et elle me bloque a fond, je push la nouvelle version un peu buggé (j'ai juste rajouté les dates, et je pense que le bug na rien a voir avec ça ), si quelqu'un peut m'en dire plus je suis partant parce que la je bloque vraiment.

J'ai essayé de voir ce qu"il se passait au debuger, mais je comprends vraiment pas pourquoi ça ne veut pas marcher.

**Comment by RemiPrevost** [comment]
Branche feature message?

**Comment by zyzo** [comment]
C'est quoi le message d'erreur, et comment reproduire ?

**Comment by jauffretp** [comment]
J'ai ouvert une issue la dessus, mais en gros pour l'avoir, j'ai l'impression qu'il suffit d'essayer d'acceder aux messages, ou d'en envoyer un, ça vient un peu de façon aléatoire.
Et oui dans la branche feature message.

**Comment by zyzo** [comment]
cf. nouvelle commit pour voir la correction. J'ai corrigé quelques typos, et capturé l'évènement `click` au lieu de `submit`. On n'a pas besoin de rafraichir la page (ce qui est le comportement par défaut de `submit`). Je sais même pas si `submit` marche car quand je met un breakpoint dans la fonction event ce n'est pas arrêté.

Je ne sais pas ce que fait le champ `datesort`, mais avant [il y avait un typo](https://github.com/SkillShareINSA/SkillShareINSA/blob/59a28a89f1d7812a6d0e2fdf66ca87cb3478234d/client/templates/inbox.js#L47). Pour le moment je met le temps en ms. 

Donc là tout marche bien. Tu peux penser à un moyen d'accéder à la page Envoi nouvelle message à un destinateur prédéfini, via un lien ? Par exemple : `/message/new/:userId` ? C'est pour l'ouvrir depuis la liste des tuteurs.

**Comment by jauffretp** [comment]
Ok merci, je vais voir ce que je peux faire. J'avais essayé de passer l'event en `click`, mais je n'avais pas réussi à le faire marcher.
Bien joué pour la typo, je pensais que `parse()`  faisait ce dont j'avais besoin mais en fait il fallait utiliser `getTime()`. 

Ce champ sert a trier les messages par ordre chronologique !

Je vais voir ce que je peux faire pour accéder a la page avec un utilisateur predefini.
