### ISSUE TITLE
Connexion directe sans passer par le CAS

### ISSUE THREAD

**Issue by RemiPrevost** [RemiPrevost/ProjectWebRTC#7]
Vous pouvez d'ores et déjà utiliser la connexion directe au serveur Meteor sans passer par le CAS.
Cette fonctionnalité se trouve sur la branche Dev. Faites un merge si voulez pouvoir l'utiliser dans la branche où vous travailler.

Jetez un coup d’œil aux quelques instructions que j'ai laissé sur la page d'accueil pour éviter de faire une mauvaise manip.

Dites moi de suite si vous trouvez des bugs que je les corrige immédiatement!

**Comment by zyzo** [comment]
J'ai testé et tout marche bien ! Par contre les utilisateurs `user_test1` , `user_test2`, `user_test3` ne sont pas là par défaut. J'ai créé un compte et ça a bien marché.

C'est quoi le plan pour ce mode de connection ? On l’intègre dans la version finale ? Et si oui, faut-il améliorer l'affichage ?

**Comment by RemiPrevost** [comment]
Oula oula on ne l'intégrera surtout pas à la version finale! Ce sont des utilisateurs Meteor qui n'ont pas de correspondance sur le serveur PHP ni le serveur CAS. Ils ne sont utiles que pour nous, pour le développement et les tests. Donc inutile d'améliorer l'affichage.

**Comment by zyzo** [comment]
Ok, c'est pas inclus dans la version finale alors. On peut l'anticiper maintenant et mettre la fonctionnalité dans un chemin à part du coup, par exemple `/adminLogin` ?

**Comment by RemiPrevost** [comment]
C'est pas une mauvaise idée! Je vais essayer de faire ça proprement !
