### ISSUE TITLE
Framework pour les tests UI : Mocha ou Selennium ?

### ISSUE THREAD

**Issue by zyzo** [RemiPrevost/ProjectWebRTC#8]
Voici le fruit de mes recherches sur le framework de test mocha. Je mets quelques liens ici pour qu'on puisse discuter demain : 

http://velocity.meteor.com/getting-started
http://mochajs.org/

Framework d'assertions : 
- should.js https://github.com/shouldjs/should.js  (Behaviour Driven Development BDD)
- http://chaijs.com/ (BDD/TDD)

NightmareJS (wrapper de Phantom.js) : 
- http://www.nightmarejs.org/

Mocha wrapper pour meteor (qui offre aussi la relance automatique des tests) : 
- https://github.com/mad-eye/meteor-mocha-web/

Si je comprends bien, MochaJS est juste un ordonnanceur/scheduler qui gère le lancement parallele et asynchrone des tests dans nodejs. Il faut phantomjs/nightmarejs pour faire le lien avec le navigateur web, et les frameworks d'assertions pour avoir des syntax agréables comme `result.should.be.exactly(42).and.be.a.Number`.

@RemiPrevost  est-ce que tu peux aussi nous documenter du côté selennium ?

**Comment by RemiPrevost** [comment]
Selenium très simple d'utilisation! (mais n'est pas un framework)

### A quoi il sert?

 Il permet de simuler automatiquement une série de cliques sur la fenêtre en cours d'utilisation. Cette série de cliques est définie au préalable par l'utilisateur qui effectue à la main les actions à automatiser pendant que le logiciel les enregistre. On peut alors lancer la série d'action automatiques. Le logiciel nous indique si la série s'est bien déroulée. Si elle ne s'est pas bien déroulée, elle est également capable de nous indiquer quelle action particulière a échouée. Ce peut par exemple être au clique sur un bouton qui n'était pas présent sur la page car ce n'est pas la bonne page qui est apparue lors du test.

### Ou se le procurer?

Selenium est une extension Firefox donc il faut d'abord installer Firefox sur sa machine. Ensuite vous pouvez télécharger l'extension à cette adresse : http://release.seleniumhq.org/selenium-ide/2.9.0/selenium-ide-2.9.0.xpi

SI le lien ne fonctionne pas allez sur [la page de téléchargement de Selenium](http://www.seleniumhq.org/download/)  et cherchez le champ `Selenium IDE`. Prenez la dernière version (actuellement 2.9.0)

### Ou trouver des tutos?

Selenium est si simple d'utilisation pour les fonctions de bases que je me suis contenté de ce [tuto video](https://www.youtube.com/watch?v=IhJgrLjljpc). 

Il y a des fonctionnalités plus avancées telles que le lancement de tests de façon périodique mais je ne me suis pas encore penché sur le sujet vu que je n'en ai pas encore trouvé d'intérêt.

**Comment by RemiPrevost** [comment]
Pour réponde à la question du topic, je pense qu'une utilisation des deux peut être intéressante! A débattre demain (enfin aujourd'hui...) !
